         continue-on-error: true
         timeout-minutes: 100
         run: |
              git config --global user.name "berkays0733"
              git config --global user.email "secrets.EMAILGIT"
              mkdir tmp && cd tmp
              git clone https://github.com/berkays0733/Kurata-Yui Kurata-Yui
       - name: Setup Erfan & Save Space
         continue-on-error: true
         timeout-minutes: 10
         run: |
              git clone --recurse-submodules https://github.com/berkays0733/ErfanGSIs ErfanGSIs
              cd Erf*; sudo apt-get --fix-broken install -y; sudo bash setup.sh
              sudo rm -rf /usr/share/dotnet/
              sudo rm -rf "/usr/local/share/boost"
	@@ -38,7 +38,7 @@ jobs:
         continue-on-error: true
         timeout-minutes: 10
         run: |
              git clone https://github.com/berkays0733/linuxshitbot Bobo
              mv Bobo/*.jar .; rm -rf Bobo
              mv *.jar BoboBot.jar
	@@ -57,10 +57,10 @@ jobs:
              touch config.prop
              echo "bot-token=${{ secrets.TOKEN }}" >> "config.prop"
              echo "bot-username=linuxshitbot" >> "config.prop"
              echo "bot-master=677702936" >> "config.prop"
              echo "bot-sf-pass=${{ secrets.SF_PASS }}" >> sf-creds.config
              echo "bot-sf-proj=berkay-gsi" >> sf-creds.config
              echo "bot-sf-user=berkay-gsi" >> sf-creds.config
              echo "bot-announcement-id=-1001178894412" >> sf-creds.config
              echo "bot-sf-host=frs.sourceforge.net" >> sf-creds.config
              echo "bot-send-announcement=true" >> sf-creds.config
              echo '["1263663104","1469015383","1032274246","1186205613","522458637","760404389","1179129272","968189873","678206065"]' >> allowed2port.json
       - name: Run Bot3
         continue-on-error: true
         timeout-minutes: 350
         run: sudo java -jar BoboBot.jar
         
       - name: Loop workflow
         continue-on-error: true
         timeout-minutes: 1
         run: |
              cd tmp/Kurata-Yui
              git commit --allow-empty -m "(LOOP): Make a forced loop"
              
       - name: Reruns
         continue-on-error: true
         timeout-minutes: 5
         run: |
              cd tmp/Kurata-Yui
              sudo apt-get install expect -y
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"aaaaaaaaaaaaaaaaaaa1\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"master -> master\"
              set timeout -10
              interact"
