name: Running bot (Master 2)
 
on: push

env:
  TZ: America/Recife

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 525600

    steps:
       - name: Checkouts
         uses: actions/checkout@master
         
       - name: Initializing environments
         continue-on-error: true
         timeout-minutes: 100
         run: |
              git config --global user.name "SkyYuko"
              git config --global user.email "secrets.EMAILGIT"
              mkdir tmp && cd tmp
              git clone https://github.com/Kurata-Yui/Kurata-Yui -b master-2 Kurata-Yui
              sudo apt-get update -y
              sudo apt-get install -y tmate openssh-client

       - name: Setup Erfan & Save Space
         continue-on-error: true
         timeout-minutes: 10
         run: |
              git clone --recurse-submodules https://github.com/YuMiGSIs/ErfanGSIs-VelanGSIs ErfanGSIs
              cd Erf*; sudo bash setup.sh
              sudo rm -rf /usr/share/dotnet/
              sudo rm -rf "/usr/local/share/boost"
              sudo rm -rf "$AGENT_TOOLSDIRECTORY"
              sudo apt-get remove -y '^ghc-8.*' '^dotnet-.*' '^llvm-.*' 'php.*' azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix zsh
              echo -e 'y\n'|ssh-keygen -q -t rsa -N "" -f ~/.ssh/id_rsa
              tmate -S /tmp/tmate.sock new-session -d; tmate -S /tmp/tmate.sock wait tmate-ready; tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}' | grep -oP "(?<=^ssh ).*" >> "$(pwd)/ssh.txt"
              export SSH="$(cat "$(pwd)/ssh.txt")"
              chmod +x telegram
              sudo install telegram /usr/bin
              telegram -M "***SSH Information***: $SSH" -c ${{ secrets.TOKEN_2 }} -t -414020390

       - name: Setup BoboBot
         continue-on-error: true
         timeout-minutes: 10
         run: |
              git clone https://${{ secrets.USERNAME }}":${{ secrets.GITTOKEN }}"@github.com/Kurata-Yui/Bot3-Jar -b ci-bot Bobo
              mv Bobo/*.jar .; rm -rf Bobo
              mv *.jar BoboBot.jar

       - name: Run Bot3 in first time
         continue-on-error: true
         timeout-minutes: 3
         run: |
               java -jar BoboBot.jar
         
       - name: Add values
         continue-on-error: true
         timeout-minutes: 1
         run: |
              rm -rf configs/config.prop
              cd configs
              touch config.prop
              echo "bot-token=${{ secrets.TOKEN_2 }}" >> "config.prop"
              echo "bot-username=yumigsis_cibot" >> "config.prop"
              echo "bot-master=946757865" >> "config.prop"
              echo "bot-sf-pass=${{ secrets.SF_PASS }}" >> sf-creds.config
              echo "bot-sf-proj=yumi-project" >> sf-creds.config
              echo "bot-sf-user=pything" >> sf-creds.config
              echo "bot-announcement-id=-1001179583442" >> sf-creds.config
              echo "bot-sf-host=frs.sourceforge.net" >> sf-creds.config
              echo "bot-send-announcement=true" >> sf-creds.config
              echo '["918317361","1377656271","968189873","1263663104"]' >> allowed2port.json
             
       - name: Run Bot3
         continue-on-error: true
         timeout-minutes: 350
         run: sudo java -jar BoboBot.jar
         
       - name: Loop workflow
         continue-on-error: true
         timeout-minutes: 1
         run: |
              cd tmp/Kurata-Yui
              echo "1" >> push.txt
              git add .
              git commit -m "(LOOP): Make a forced loop"
              
       - name: Reruns
         continue-on-error: true
         timeout-minutes: 5
         run: |
              cd tmp/Kurata-Yui
              sudo apt-get install expect -y
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"yukosky\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"master-2 -> master-2\"
              set timeout -10
              interact"
